version: '3'

services:
  db:
    image: library/postgres:14-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
      - ./data/cap_zrp.com.br:/dump

  postgrest:
    image: postgrest/postgrest:latest
    hostname: api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    depends_on:
      - proxy
    env_file:
      - .env

  proxy:
    depends_on:
      - db
    image: nginx:latest
    ports:
      - "3001:3001"
    volumes:
      - "./proxy/nginx.conf:/etc/nginx/conf.d/default.conf"

  pgadmin4:
    image: dpage/pgadmin4
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/pgadmin/storage
    ports:
      - "6002:80"
    depends_on:
      - db

  postgraphql:
    profiles:
      - graphql
    image: graphile/postgraphile
    ports:
      - 5000:5000
    command: --connection postgres://postgres:cap@db:5432/dvdrental --schema api --watch --enhance-graphiql
volumes:
  pgdata:
