version: '3'

volumes:
  pgdata:
    driver: local

services:
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://postgres:cap@db:5432/dvdrentals
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: postgres #In production this role should not be the same as the one used for the connection
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
    networks:
      - workshop-network

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/
    networks:
      - workshop-network

  db:
    image: library/postgres:13-alpine
    environment:
      POSTGRES_DB: dvdrentals
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "cap"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - workshop-network

  pgadmin4:
    image: dpage/pgadmin4:5.6
    environment:
      PGADMIN_DEFAULT_EMAIL: "cap@zrp.com.br"
      PGADMIN_DEFAULT_PASSWORD: "cap"
    volumes:
      - ./data:/var/lib/pgadmin/storage
    ports:
      - "6002:80"
    depends_on:
      - db
    networks:
      - workshop-network

networks:
  workshop-network:
    driver: bridge
