#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;

  GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ${PGRST_DB_SCHEMA} TO ${ROLE_USER};
EOSQL
